// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfAbtHL4dzne9TtrpefWFrOT1FA2k__X4',
    appId: '1:493494009350:web:236f8172671d9d67740d87',
    messagingSenderId: '493494009350',
    projectId: 'thepastrypath-app',
    authDomain: 'thepastrypath-app.firebaseapp.com',
    databaseURL: 'https://thepastrypath-app-default-rtdb.firebaseio.com',
    storageBucket: 'thepastrypath-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt4Uet2VxiVsmo7WE0mRC96AkXbUxJMAI',
    appId: '1:493494009350:android:ce6246c2595d2709740d87',
    messagingSenderId: '493494009350',
    projectId: 'thepastrypath-app',
    storageBucket: 'thepastrypath-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnetetZWtijZ5LiJ1_gsleLhsjPqMK1g8',
    appId: '1:493494009350:ios:7215063cba50938a740d87',
    messagingSenderId: '493494009350',
    projectId: 'thepastrypath-app',
    storageBucket: 'thepastrypath-app.firebasestorage.app',
    iosBundleId: 'com.example.thepastrypath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnetetZWtijZ5LiJ1_gsleLhsjPqMK1g8',
    appId: '1:493494009350:ios:7215063cba50938a740d87',
    messagingSenderId: '493494009350',
    projectId: 'thepastrypath-app',
    storageBucket: 'thepastrypath-app.firebasestorage.app',
    iosBundleId: 'com.example.thepastrypath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfAbtHL4dzne9TtrpefWFrOT1FA2k__X4',
    appId: '1:493494009350:web:bc93adbe9bb96a54740d87',
    messagingSenderId: '493494009350',
    projectId: 'thepastrypath-app',
    authDomain: 'thepastrypath-app.firebaseapp.com',
    storageBucket: 'thepastrypath-app.firebasestorage.app',
  );
}
